import produce from 'immer';

import { CHANGE_DATE, GET_DATES_BY_PERSON_ID } from '@/containers/DateSelector/constants';
import { REQUEST_STATUS } from '@/utils/constants';

export const INITIAL_STATE = CONSTANTS => ({
  [CONSTANTS.REDUCER_KEY.RESULTS]: [],
  [CONSTANTS.REDUCER_KEY.RESULTS_BY_RANGE]: [],
  [CONSTANTS.REDUCER_KEY.STATUS]: {
    [CONSTANTS.REDUCER_KEY.RESULTS]: REQUEST_STATUS.LOADING,
    [CONSTANTS.REDUCER_KEY.RESULTS_BY_RANGE]: REQUEST_STATUS.LOADING
  }
});

/* eslint-disable default-case, no-param-reassign */
export const defaultProduce = (CONSTANTS, initialState) => (state = initialState, action) =>
  produce(state, draft => {
    switch (action.type) {
      case CONSTANTS.ACTIONS.LOAD_SUCCESS:
        draft[CONSTANTS.REDUCER_KEY.RESULTS] = action.payload;
        draft[CONSTANTS.REDUCER_KEY.STATUS][CONSTANTS.REDUCER_KEY.RESULTS] = REQUEST_STATUS.LOADED;
        break;
      case CONSTANTS.ACTIONS.DATE_RANGE_LOAD_SUCCESS:
        draft[CONSTANTS.REDUCER_KEY.RESULTS_BY_RANGE] = action.payload;
        draft[CONSTANTS.REDUCER_KEY.STATUS][CONSTANTS.REDUCER_KEY.RESULTS_BY_RANGE] =
          REQUEST_STATUS.LOADED;
        break;
      case CONSTANTS.ACTIONS.LOAD_ERROR:
        draft[CONSTANTS.REDUCER_KEY.STATUS][CONSTANTS.REDUCER_KEY.RESULTS] = REQUEST_STATUS.ERROR;
        break;
      case CONSTANTS.ACTIONS.DATE_RANGE_LOAD_ERROR:
        draft[CONSTANTS.REDUCER_KEY.STATUS][CONSTANTS.REDUCER_KEY.RESULTS_BY_RANGE] =
          REQUEST_STATUS.ERROR;
        break;
      case GET_DATES_BY_PERSON_ID:
        draft[CONSTANTS.REDUCER_KEY.STATUS][CONSTANTS.REDUCER_KEY.RESULTS] = REQUEST_STATUS.LOADING;
        draft[CONSTANTS.REDUCER_KEY.STATUS][CONSTANTS.REDUCER_KEY.RESULTS_BY_RANGE] =
          REQUEST_STATUS.LOADING;
        break;
      case CHANGE_DATE:
        draft[CONSTANTS.REDUCER_KEY.STATUS][CONSTANTS.REDUCER_KEY.RESULTS_BY_RANGE] =
          REQUEST_STATUS.LOADING;
        break;
    }
  });
