export const STATE_KEY = {
  MAIN: 'CoodrinationJumpsDiffVerticalTest',
  COORDINATION_JUMPS_DIFF_VERTICAL: 'CoodrinationJumpsDiffVertical',
  COORDINATION_JUMPS_DIFF_VERTICAL_BY_RANGE: 'CoodrinationJumpsDiffVerticalByRange'
};

export const API_PATH = 'verticaljumps';

export const COORDINATION_JUMPS_DIFF_VERTICAL_LOAD_SUCCESS = `athleteTests/${STATE_KEY.MAIN}/COORDINATION_JUMPS_DIFF_VERTICAL_LOAD_SUCCESS`;
export const COORDINATION_JUMPS_DIFF_VERTICAL_LOAD_ERROR = `athleteTests/${STATE_KEY.MAIN}/COORDINATION_JUMPS_DIFF_VERTICAL_LOAD_ERROR`;

export const COORDINATION_JUMPS_DIFF_VERTICAL_BY_DATE_RANGE_LOAD_SUCCESS = `athleteTests/${STATE_KEY.MAIN}/COORDINATION_JUMPS_DIFF_VERTICAL_BY_DATE_RANGE_LOAD_SUCCESS`;
export const COORDINATION_JUMPS_DIFF_VERTICAL_BY_DATE_RANGE_LOAD_ERROR = `athleteTests/${STATE_KEY.MAIN}/COORDINATION_JUMPS_DIFF_VERTICAL_BY_DATE_RANGE_LOAD_ERROR`;
