export const STATE_KEY = {
  MAIN: 'FlexibilityShouldersTest',
  RESULTS: 'results',
  RESULTS_BY_RANGE: 'resultsByRange'
};

export const RESULT_KEY = {
  LEFT_SHOULDER: 'leftShoulder',
  RIGHT_SHOULDER: 'rightShoulder',
  WRING: 'wring'
};

export const API_PATH = 'flexibility';

export const API_TYPE = 'SHOULDERS';

export const FLEXIBILITY_SHOULDERS_LOAD_SUCCESS = `athleteTests/${STATE_KEY.MAIN}/FLEXIBILITY_SHOULDERS_LOAD_SUCCESS`;
export const FLEXIBILITY_SHOULDERS_LOAD_ERROR = `athleteTests/${STATE_KEY.MAIN}/FLEXIBILITY_SHOULDERS_LOAD_ERROR`;

export const FLEXIBILITY_SHOULDERS_BY_DATE_RANGE_LOAD_SUCCESS = `athleteTests/${STATE_KEY.MAIN}/FLEXIBILITY_SHOULDERS_BY_DATE_RANGE_LOAD_SUCCESS`;
export const FLEXIBILITY_SHOULDERS_BY_DATE_RANGE_LOAD_ERROR = `athleteTests/${STATE_KEY.MAIN}/FLEXIBILITY_SHOULDERS_BY_DATE_RANGE_LOAD_ERROR`;
