export const STATE_KEY = {
  MAIN: 'StressAndRecoveryTest',
  RESULTS: 'results',
  RESULTS_BY_RANGE: 'resultByRange'
};

export const API_PATH = 'stressAndRecovery';

export const STRESS_AND_RECOVERY_LOAD_SUCCESS = `athleteTests/${STATE_KEY.MAIN}/STRESS_AND_RECOVERY_LOAD_SUCCESS`;
export const STRESS_AND_RECOVERY_LOAD_ERROR = `athleteTests/${STATE_KEY.MAIN}/STRESS_AND_RECOVERY_LOAD_ERROR`;
export const STRESS_AND_RECOVERY_BY_DATE_RANGE_LOAD_SUCCESS = `athleteTests/${STATE_KEY.MAIN}/STRESS_AND_RECOVERY_BY_DATE_RANGE_LOAD_SUCCESS`;
export const STRESS_AND_RECOVERY_BY_DATE_RANGE_LOAD_ERROR = `athleteTests/${STATE_KEY.MAIN}/STRESS_AND_RECOVERY_BY_DATE_RANGE_LOAD_ERROR`;
