export const BACK_FORWARD_RUN_SAVE_FORM = `athleteTests/BackForwardRunInputForm/BACK_FORWARD_RUN_SAVE_FORM`;
export const BACK_FORWARD_RUN_SAVE_FORM_ERROR = `athleteTests/BackForwardRunInputForm/BACK_FORWARD_RUN_SAVE_FORM_ERROR`;
export const BACK_FORWARD_RUN_SAVE_FORM_SUCCESS = `athleteTests/BackForwardRunInputForm/BACK_FORWARD_RUN_SAVE_FORM_SUCCESS`;
