export const STATE_KEY = {
  MAIN: 'CoordinationJumpsDiffHorizontalTest',
  COORDINATION_JUMPS_DIFF_HORIZONTAL: 'CoordinationJumpsDiffHorizontal',
  COORDINATION_JUMPS_DIFF_HORIZONTAL_BY_RANGE: 'CoordinationJumpsDiffHorizontalByRange'
};

export const RESULT_KEY = {
  JUMP_1: 'jump1',
  JUMP_2: 'jump2',
  JUMP_3: 'jump3',
  JUMP_4: 'jump4',
  JUMP_5: 'jump5',
  JUMP_6: 'jump6'
};

export const API_PATH = 'horizontaljumps';

export const COORDINATION_JUMPS_DIFF_HORIZONTAL_LOAD_SUCCESS = `athleteTests/${STATE_KEY.MAIN}/COORDINATION_JUMPS_DIFF_HORIZONTAL_LOAD_SUCCESS`;
export const COORDINATION_JUMPS_DIFF_HORIZONTAL_LOAD_ERROR = `athleteTests/${STATE_KEY.MAIN}/COORDINATION_JUMPS_DIFF_HORIZONTAL_LOAD_ERROR`;

export const COORDINATION_JUMPS_DIFF_HORIZONTAL_BY_DATE_RANGE_LOAD_SUCCESS = `athleteTests/${STATE_KEY.MAIN}/COORDINATION_JUMPS_DIFF_HORIZONTAL_BY_DATE_RANGE_LOAD_SUCCESS`;
export const COORDINATION_JUMPS_DIFF_HORIZONTAL_BY_DATE_RANGE_LOAD_ERROR = `athleteTests/${STATE_KEY.MAIN}/COORDINATION_JUMPS_DIFF_HORIZONTAL_BY_DATE_RANGE_LOAD_ERROR`;
