import CONSTANTS from '@/utils/interfaces/constants';

const REDUCER_KEY = 'Tremor';
const API_PATH = 'getTestTremorDynamic';
const API_TYPE = 1;
const GRAPHQL_BACK_TYPE = 1;

export const RESULT_KEY = {
  DURATION_BEFORE: 'durBefore',
  TOUCH_BEFORE: 'touchBefore',
  DURATION_AFTER_30: 'durAfter30',
  TOUCH_AFTER_30: 'touchAfter30',
  HEART_AFTER_30_START: 'heartAfter30Start',
  HEART_AFTER_30_END: 'heartAfter30End',
  DURATION_AFTER_150: 'durAfter150',
  TOUCH_AFTER_150: 'touchAfter150',
  HEART_AFTER_150_START: 'heartAfter150Start',
  HEART_AFTER_150_END: 'heartAfter150End',
  DURATION_AVERAGE: 'durAverage'
};

export const GRAPHQL_KEYS = [
  RESULT_KEY.DURATION_BEFORE,
  RESULT_KEY.TOUCH_BEFORE,
  RESULT_KEY.DURATION_AFTER_30,
  RESULT_KEY.TOUCH_AFTER_30,
  RESULT_KEY.HEART_AFTER_30_START,
  RESULT_KEY.HEART_AFTER_30_END,
  RESULT_KEY.DURATION_AFTER_150,
  RESULT_KEY.TOUCH_AFTER_150,
  RESULT_KEY.HEART_AFTER_150_START,
  RESULT_KEY.HEART_AFTER_150_END,
  RESULT_KEY.DURATION_AVERAGE
]

export const LABELS = {
  [RESULT_KEY.KOG]: 'Когнитивная'
};

export default CONSTANTS(REDUCER_KEY, API_PATH, API_TYPE, undefined, GRAPHQL_BACK_TYPE, GRAPHQL_KEYS);
