export const STATE_KEY = {
  MAIN: 'MotilityJumpsDiffVerticalTest',
  MOTILITY_JUMPS_DIFF_VERTICAL: 'MotilityJumpsDiffVertical',
  MOTILITY_JUMPS_DIFF_VERTICAL_BY_RANGE: 'MotilityJumpsDiffVerticalByRange'
};

export const API_PATH = 'verticaljumps';

export const MOTILITY_JUMPS_DIFF_VERTICAL_LOAD_SUCCESS = `athleteTests/${STATE_KEY.MAIN}/MOTILITY_JUMPS_DIFF_VERTICAL_LOAD_SUCCESS`;
export const MOTILITY_JUMPS_DIFF_VERTICAL_LOAD_ERROR = `athleteTests/${STATE_KEY.MAIN}/MOTILITY_JUMPS_DIFF_VERTICAL_LOAD_ERROR`;

export const MOTILITY_JUMPS_DIFF_VERTICAL_BY_DATE_RANGE_LOAD_SUCCESS = `athleteTests/${STATE_KEY.MAIN}/MOTILITY_JUMPS_DIFF_VERTICAL_BY_DATE_RANGE_LOAD_SUCCESS`;
export const MOTILITY_JUMPS_DIFF_VERTICAL_BY_DATE_RANGE_LOAD_ERROR = `athleteTests/${STATE_KEY.MAIN}/MOTILITY_JUMPS_DIFF_VERTICAL_BY_DATE_RANGE_LOAD_ERROR`;
