export const STATE_KEY = {
  MAIN: 'SportMotivationScaleTest',
  RESULTS: 'results',
  RESULTS_BY_RANGE: 'resultByRange'
};

export const API_PATH = 'sms';

export const MOTIVATION_KEY = {
  UN: 'un',
  S: 's',
  PE: 'pe',
  SC: 'sc',
  D: 'd',
  SO: 'so',
  OM: 'om'
};

export const SPORT_MOTIVATION_SCALE_LOAD_SUCCESS = `athleteTests/${STATE_KEY.MAIN}/SPORT_MOTIVATION_SCALE_LOAD_SUCCESS`;
export const SPORT_MOTIVATION_SCALE_LOAD_ERROR = `athleteTests/${STATE_KEY.MAIN}/SPORT_MOTIVATION_SCALE_LOAD_ERROR`;
export const SPORT_MOTIVATION_SCALE_BY_DATE_RANGE_LOAD_SUCCESS = `athleteTests/${STATE_KEY.MAIN}/SPORT_MOTIVATION_SCALE_BY_DATE_RANGE_LOAD_SUCCESS`;
export const SPORT_MOTIVATION_SCALE_BY_DATE_RANGE_LOAD_ERROR = `athleteTests/${STATE_KEY.MAIN}/SPORT_MOTIVATION_SCALE_BY_DATE_RANGE_LOAD_ERROR`;
