export const STATE_KEY = {
  MAIN: 'SpeedAndPowerThreeJumpsTest',
  SPEED_AND_POWER_THREE_JUMPS: 'SpeedAndPowerThreeJumps',
  SPEED_AND_POWER_THREE_JUMPS_BY_RANGE: 'SpeedAndPowerThreeJumpsByRange'
};

export const API_PATH = 'threejumps';

export const SPEED_AND_POWER_THREE_JUMPS_LOAD_SUCCESS = `athleteTests/${STATE_KEY.MAIN}/SPEED_AND_POWER_THREE_JUMPS_LOAD_SUCCESS`;
export const SPEED_AND_POWER_THREE_JUMPS_LOAD_ERROR = `athleteTests/${STATE_KEY.MAIN}/SPEED_AND_POWER_THREE_JUMPS_LOAD_ERROR`;

export const SPEED_AND_POWER_THREE_JUMPS_BY_DATE_RANGE_LOAD_SUCCESS = `athleteTests/${STATE_KEY.MAIN}/SPEED_AND_POWER_THREE_JUMPS_BY_DATE_RANGE_LOAD_SUCCESS`;
export const SPEED_AND_POWER_THREE_JUMPS_BY_DATE_RANGE_LOAD_ERROR = `athleteTests/${STATE_KEY.MAIN}/SPEED_AND_POWER_THREE_JUMPS_BY_DATE_RANGE_LOAD_ERROR`;
