export const HEADER_TYPE = {
  TEXT: 'TEXT',
  ICON_DESCRIPTION: 'ICON_DESCRIPTION',
  TWO_TITLES: 'TWO_TITLES'
};

export const CELL_TYPE = {
  TEXT: 'TEXT',
  TEXT_BOLD: 'TEXT_BOLD',
  TEXT_DOUBLE: 'TEXT_DOUBLE',
  TEXT_TRIPLE: 'TEXT_TRIPLE',
  ZONE: 'ZONE'
};
